Vagrant.configure("2") do |config|
  config.vm.box = "Ubuntu23-Gnome-minimal"

  config.vm.provider :libvirt do |libvirt|
    # libvirt.default_prefix = ""
    libvirt.graphics_type = "spice"
    libvirt.video_type = 'qxl'
  end

  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "ansible/vagrant.yml"
  end
end
