Vagrant.configure("2") do |config|
  config.vm.box = "Ubuntu-Desktop-minimal"
  # config.vm.box = "Ubuntu-Gnome-minimal"

  config.vm.provider :libvirt do |libvirt|
    # libvirt.default_prefix = ""
    libvirt.graphics_type = "spice"
    libvirt.video_type = 'qxl'
    libvirt.cpus = 4
    libvirt.cputopology :sockets => '1', :cores => '4', :threads => '1'
  end

  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "ansible/vagrant.yml"
  end
end
