---
roles:
# from galaxy.ansible.com
# AptCacherNG
- name: UniInc.AptCacherNg-Server-inContainer
- name: UniInc.AptCacherNg-Client

# Vagrant dev environment
- name: UniInc.AptCacherNg-fix-Vagrant
- name: UniInc.Ubuntu-needrestart-disable
- name: UniInc.Gnome-Desktop-minimal

# Dart
- name: UniInc.Dart

# Flutter
- name: UniInc.Android-sdkmanager
- name: UniInc.Flutter-SDK
- name: UniInc.Visual-Studio-Code
- name: UniInc.Flutter-VSCode

# Android Emulator image
- name: UniInc.Android-AVD

# optional
- name: UniInc.Flutter-VSCode-Extensions-extra
- name: UniInc.Android-Studio

# Android Studio SDK Components
- name: UniInc.Flutter-Android-Studio-SDK-components
# TODO: untested! https://github.com/Open-IDE/ansible-role-Flutter-Android-Studio-SDK-components
