- name: Flutter Dev on Ubuntu
  hosts: localhost
  remote_user: vagrant
  vars:
    debug: false
    android_emulator: false

  roles:
    - UniInc.Android-sdkmanager
    - UniInc.VSCode-Flutter
    # Debug:
    # - ansible-role-VSCode-Flutter

  # Option:
    # - UniInc.Android-Studio
