- name: Flutter Dev on Ubuntu
  hosts: localhost
  vars:
    debug: false
    android_emulator: false

  roles:
    - UniInc.Android-sdkmanager
    - UniInc.Flutter-SDK
    - UniInc.Flutter-VSCode
    # optional
    - Flutter-VSCode-Extensions-extra
    # Debug:
    # - ansible-role-VSCode-Flutter

  # Option:
    # - UniInc.Android-Studio
