- name: Vagrant Ubuntu
  hosts: all
  remote_user: vagrant
  vars:
    debug: false
    android_emulator: false

  roles:
    - UniInc.AptCacherNg-fix-Vagrant
    - UniInc.AptCacherNg-Client
    - UniInc.Android-sdkmanager
    - UniInc.Flutter-SDK
    - UniInc.Flutter-VSCode
    # optional
    - Flutter-VSCode-Extensions-extra
    # Debug:
    # - ansible-role-VSCode-Flutter

  # Option:
    # - UniInc.Android-Studio
