- name: Vagrant Ubuntu
  hosts: all
  remote_user: vagrant
  vars:
    debug: false
    android_emulator: false

  roles:
    - UniInc.AptCacherNg-fix-Vagrant
    - UniInc.AptCacherNg-Client
    - UniInc.VSCode-Flutter
    # Debug:
    # - ansible-role-VSCode-Flutter

  # Option:
    # - UniInc.Android-Studio
